version: '3.5'

services:

  consignment-cli:
    build: ./cli
    container_name: x-cli-consignment
    networks:
      - ser-network
    depends_on:
      - shippy-service-consignment

  shippy-service-consignment:
    restart: always # ensures the container will restart on crash
    container_name: "shippy-service-consignment"
    build: ./ser
    ports:
      - 50051 # exposing this port on the docker network only, not host
    depends_on:
      - datastore
    networks:
      - db-network
      - ser-network
    environment:
      DB_HOST: "mongodb://datastore:27017"
      MICRO_ADDRESS: ":50051"

  datastore:
    image: mongo:latest
    container_name: datastore
    restart: always # ensures the container will restart on crash
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    networks:
      - db-network
    ports:
      - 27017
    command: mongod --logpath=/dev/null

networks:
  db-network:
    name: db-network
  ser-network:
    name: ser-network